-- GuildUp 다중 게임/외부 서비스 도메인 리팩터링용 PostgreSQL 수동 마이그레이션.
-- 애플리케이션이 자동 실행하지 않는다. 운영 DB 백업과 실행 대상 확인 후 직접 실행한다.

BEGIN;

-- Community 생성 시각 추가 및 기존 행 보정
ALTER TABLE communities
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE;

UPDATE communities
SET created_at = CURRENT_TIMESTAMP
WHERE created_at IS NULL;

ALTER TABLE communities
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN created_at SET NOT NULL;

-- GuildUp 자체 사용자
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- GuildUp 사용자 외부 계정
CREATE TABLE IF NOT EXISTS user_external_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(50) NOT NULL,
    external_user_id VARCHAR(255) NOT NULL,
    external_username VARCHAR(255),
    CONSTRAINT fk_user_external_account_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_user_external_account_user_provider
        UNIQUE (user_id, provider),
    CONSTRAINT uk_user_external_account_provider_id
        UNIQUE (provider, external_user_id)
);

-- 커뮤니티 활동 게임
CREATE TABLE IF NOT EXISTS community_games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id BIGINT NOT NULL,
    game_type VARCHAR(50) NOT NULL,
    CONSTRAINT fk_community_game_community
        FOREIGN KEY (community_id) REFERENCES communities (id) ON DELETE CASCADE,
    CONSTRAINT uk_community_game
        UNIQUE (community_id, game_type)
);

-- GuildUp 사용자와 커뮤니티의 관리 관계
CREATE TABLE IF NOT EXISTS community_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,
    CONSTRAINT fk_community_user_community
        FOREIGN KEY (community_id) REFERENCES communities (id) ON DELETE CASCADE,
    CONSTRAINT fk_community_user_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_community_user
        UNIQUE (community_id, user_id)
);

-- 클랜원의 외부 서비스 계정
CREATE TABLE IF NOT EXISTS community_member_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_member_id BIGINT NOT NULL,
    provider VARCHAR(50) NOT NULL,
    external_user_id VARCHAR(255) NOT NULL,
    external_username VARCHAR(255),
    CONSTRAINT fk_community_member_account_member
        FOREIGN KEY (community_member_id) REFERENCES community_members (id) ON DELETE CASCADE,
    CONSTRAINT uk_community_member_account_provider
        UNIQUE (community_member_id, provider)
);

CREATE INDEX IF NOT EXISTS idx_community_member_account_provider_external_id
    ON community_member_accounts (provider, external_user_id);

-- Community에 완전히 종속되는 기존 행도 부모 삭제 시 함께 정리되도록 FK를 맞춘다.
DO $$
DECLARE
    existing_constraint TEXT;
BEGIN
    SELECT tc.constraint_name
    INTO existing_constraint
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
      ON tc.constraint_schema = kcu.constraint_schema
     AND tc.constraint_name = kcu.constraint_name
    WHERE tc.table_schema = current_schema()
      AND tc.table_name = 'community_members'
      AND tc.constraint_type = 'FOREIGN KEY'
      AND kcu.column_name = 'community_id'
    LIMIT 1;

    IF existing_constraint IS NOT NULL THEN
        EXECUTE format(
            'ALTER TABLE community_members DROP CONSTRAINT %I',
            existing_constraint
        );
    END IF;

    ALTER TABLE community_members
        ADD CONSTRAINT fk_community_member_community
        FOREIGN KEY (community_id) REFERENCES communities (id) ON DELETE CASCADE;
END $$;

DO $$
DECLARE
    existing_constraint TEXT;
BEGIN
    SELECT tc.constraint_name
    INTO existing_constraint
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
      ON tc.constraint_schema = kcu.constraint_schema
     AND tc.constraint_name = kcu.constraint_name
    WHERE tc.table_schema = current_schema()
      AND tc.table_name = 'discord_community_connections'
      AND tc.constraint_type = 'FOREIGN KEY'
      AND kcu.column_name = 'community_id'
    LIMIT 1;

    IF existing_constraint IS NOT NULL THEN
        EXECUTE format(
            'ALTER TABLE discord_community_connections DROP CONSTRAINT %I',
            existing_constraint
        );
    END IF;

    ALTER TABLE discord_community_connections
        ADD CONSTRAINT fk_discord_community_connection_community
        FOREIGN KEY (community_id) REFERENCES communities (id) ON DELETE CASCADE;
END $$;

-- 기존 community_members.discord_user_id를 Discord 외부 계정으로 먼저 이전한다.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'community_members'
          AND column_name = 'discord_user_id'
    ) THEN
        EXECUTE '
            INSERT INTO community_member_accounts (
                community_member_id,
                provider,
                external_user_id,
                external_username
            )
            SELECT
                id,
                ''DISCORD'',
                discord_user_id,
                NULL
            FROM community_members
            WHERE discord_user_id IS NOT NULL
              AND BTRIM(discord_user_id) <> ''''
            ON CONFLICT (community_member_id, provider)
            DO UPDATE SET external_user_id = EXCLUDED.external_user_id
        ';
    END IF;
END $$;

-- communities의 기존 Discord 서버 연결도 별도 연결 테이블에 없는 경우 보존한다.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'communities'
          AND column_name = 'discord_guild_id'
    ) THEN
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'communities'
              AND column_name = 'discord_member_role_id'
        ) THEN
            EXECUTE '
                INSERT INTO discord_community_connections (
                    community_id,
                    discord_guild_id,
                    discord_guild_name,
                    discord_member_role_id
                )
                SELECT
                    id,
                    discord_guild_id,
                    NULL,
                    discord_member_role_id
                FROM communities
                WHERE discord_guild_id IS NOT NULL
                  AND BTRIM(discord_guild_id) <> ''''
                ON CONFLICT DO NOTHING
            ';
        ELSE
            EXECUTE '
                INSERT INTO discord_community_connections (
                    community_id,
                    discord_guild_id,
                    discord_guild_name,
                    discord_member_role_id
                )
                SELECT
                    id,
                    discord_guild_id,
                    NULL,
                    NULL
                FROM communities
                WHERE discord_guild_id IS NOT NULL
                  AND BTRIM(discord_guild_id) <> ''''
                ON CONFLICT DO NOTHING
            ';
        END IF;
    END IF;
END $$;

-- 데이터 이전이 끝난 뒤 핵심 테이블의 외부 서비스 전용 컬럼을 제거한다.
ALTER TABLE community_members
    DROP COLUMN IF EXISTS discord_user_id;

ALTER TABLE communities
    DROP COLUMN IF EXISTS discord_guild_id;

ALTER TABLE communities
    DROP COLUMN IF EXISTS discord_member_role_id;

COMMIT;
