-- 기존 monitoring_events에 활동 조회 필터용 nullable 필드와 syncId 인덱스만 추가한다.
-- Hibernate ddl-auto=update는 기존 enum CHECK를 확장하지 않으므로 애플리케이션 배포 전에 실행한다.
BEGIN;
ALTER TABLE monitoring_events ADD COLUMN IF NOT EXISTS activity_game_type VARCHAR(32);
ALTER TABLE monitoring_events ADD COLUMN IF NOT EXISTS duration_ms BIGINT;
ALTER TABLE monitoring_events DROP CONSTRAINT IF EXISTS monitoring_events_event_code_check;
ALTER TABLE monitoring_events ADD CONSTRAINT monitoring_events_event_code_check CHECK (event_code IN (
    'HTTP_5XX', 'PUBG_API_RATE_LIMIT', 'PUBG_API_TIMEOUT',
    'PUBG_API_RETRY', 'PUBG_API_CLIENT_ERROR', 'PUBG_API_SERVER_ERROR',
    'PUBG_API_FAILED', 'COMMUNITY_ACTIVITY_SYNC_FAILED', 'ACTIVITY_SYNC_QUEUED',
    'ACTIVITY_SYNC_STARTED', 'ACTIVITY_SYNC_PLAYER_FETCH_STARTED', 'ACTIVITY_SYNC_PLAYER_FETCH_COMPLETED',
    'ACTIVITY_SYNC_PLAYER_FETCH_FAILED', 'ACTIVITY_SYNC_MATCH_FETCH_STARTED', 'ACTIVITY_SYNC_MATCH_FETCH_COMPLETED',
    'ACTIVITY_SYNC_MATCH_FETCH_FAILED', 'ACTIVITY_SYNC_CALCULATION_STARTED', 'ACTIVITY_SYNC_CALCULATION_COMPLETED',
    'ACTIVITY_SYNC_SAVE_STARTED', 'ACTIVITY_SYNC_SAVE_COMPLETED', 'ACTIVITY_SYNC_SAVE_FAILED',
    'ACTIVITY_SYNC_COMPLETED', 'ACTIVITY_SYNC_FAILED', 'ACTIVITY_SYNC_SUPERSEDED',
    'PUBG_RATE_LIMIT_RECOVERED', 'BINGO_AGGREGATION_FAILED', 'BINGO_PARTIAL_FAILURE',
    'BINGO_SLOW_AGGREGATION', 'KILL_COMPETITION_INTERIM_FAILED', 'KILL_COMPETITION_SETTLEMENT_FAILED',
    'KILL_COMPETITION_RESULT_PENDING', 'KILL_COMPETITION_RESULT_PENDING_STALE', 'DISCORD_API_FAILED',
    'DISCORD_RATE_LIMIT', 'JDA_CONNECTION_FAILED', 'DISCORD_GUILD_CONNECTION_FAILED',
    'DISCORD_OAUTH_FAILED', 'DISCORD_GUILD_MISMATCH', 'DISCORD_MEMBER_LOOKUP_FAILED',
    'DATABASE_ERROR', 'DATABASE_POOL_EXHAUSTED', 'UNEXPECTED_EXCEPTION'
)) NOT VALID;
COMMIT;
ALTER TABLE monitoring_events VALIDATE CONSTRAINT monitoring_events_event_code_check;

-- transaction 밖에서 생성해 기존 운영 테이블의 쓰기 잠금을 최소화한다.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_monitoring_events_reference_occurred_at
    ON monitoring_events (reference_id, occurred_at, id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_monitoring_events_activity_game_occurred_at
    ON monitoring_events (activity_game_type, occurred_at DESC) WHERE activity_game_type IS NOT NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_monitoring_events_duration_occurred_at
    ON monitoring_events (duration_ms, occurred_at DESC) WHERE duration_ms IS NOT NULL;
