-- PostgreSQL. 운영 환경에는 별도로 적용할 파일이며 자동 실행하지 않는다.
-- 기존 기능은 SMTP 전용으로 문의 테이블이 없었다. 메일함 기록은 그대로 보존한다.
-- 기존 users를 참조하며 문의/사용자/커뮤니티 데이터를 삭제하지 않는다.
BEGIN;
CREATE TABLE IF NOT EXISTS feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    author_nickname VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('SERVICE', 'FEATURE', 'BUG', 'ETC')),
    title VARCHAR(100) NOT NULL,
    content VARCHAR(3000) NOT NULL,
    -- 삭제된 커뮤니티의 접수 당시 context도 보존하도록 FK/cascade 없이 저장한다.
    community_id BIGINT,
    community_name VARCHAR(255),
    page_route VARCHAR(300),
    status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED'
        CHECK (status IN ('RECEIVED', 'IN_PROGRESS', 'ANSWERED', 'CLOSED')),
    answer VARCHAR(3000),
    answered_at TIMESTAMP WITH TIME ZONE,
    answered_by_user_id BIGINT REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
-- 동일 스키마를 사용한 기존 문의가 있으면 community_id 값은 보존하고 필수 제약만 완화한다.
ALTER TABLE feedbacks ALTER COLUMN community_id DROP NOT NULL;
CREATE INDEX IF NOT EXISTS idx_feedbacks_user_created ON feedbacks(user_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_feedbacks_created ON feedbacks(created_at, id);
COMMIT;

-- 적용 전후 읽기 전용 확인용(필요 시 별도 실행):
-- SELECT COUNT(*), COUNT(community_id) FROM feedbacks;
-- SELECT is_nullable FROM information_schema.columns
--   WHERE table_schema = 'public' AND table_name = 'feedbacks' AND column_name = 'community_id';
