-- PostgreSQL: 애플리케이션 배포 전에 실행한다. 기존 users/외부계정/커뮤니티 데이터는 수정하지 않는다.
BEGIN;
CREATE TABLE IF NOT EXISTS user_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_credential_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_credential_user UNIQUE (user_id),
    CONSTRAINT uk_user_credential_email UNIQUE (email),
    CONSTRAINT ck_user_credential_email_normalized CHECK (email = lower(btrim(email)))
);
-- DB 외부에서 잘못된 비정규화 이메일을 넣더라도 대소문자/공백 중복을 차단한다.
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_credential_email_normalized ON user_credentials (lower(btrim(email)));
-- 외부 계정의 기존 UNIQUE 계약을 유지한다. 기존 중복이 있다면 실패하며 데이터를 자동 정리하지 않는다.
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_external_account_provider_id
    ON user_external_accounts (provider, external_user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_external_account_user_provider
    ON user_external_accounts (user_id, provider);
COMMIT;
