-- 배포 전 실행: Hibernate ddl-auto=update는 기존 enum CHECK를 확장하지 않는다.
-- 활동 조회 실패 코드를 허용하고, 기존 이벤트와 다른 제약 및 인덱스는 유지한다.
BEGIN;
ALTER TABLE monitoring_events
    DROP CONSTRAINT IF EXISTS monitoring_events_event_code_check;
ALTER TABLE monitoring_events
    ADD CONSTRAINT monitoring_events_event_code_check CHECK (event_code IN (
        'HTTP_5XX',
        'PUBG_API_RATE_LIMIT', 'PUBG_API_TIMEOUT', 'PUBG_API_RETRY', 'PUBG_API_CLIENT_ERROR',
        'PUBG_API_SERVER_ERROR', 'PUBG_API_FAILED', 'COMMUNITY_ACTIVITY_SYNC_FAILED',
        'BINGO_AGGREGATION_FAILED', 'BINGO_PARTIAL_FAILURE', 'BINGO_SLOW_AGGREGATION',
        'KILL_COMPETITION_INTERIM_FAILED', 'KILL_COMPETITION_SETTLEMENT_FAILED',
        'KILL_COMPETITION_RESULT_PENDING', 'KILL_COMPETITION_RESULT_PENDING_STALE',
        'DISCORD_API_FAILED', 'DISCORD_RATE_LIMIT', 'JDA_CONNECTION_FAILED',
        'DISCORD_GUILD_CONNECTION_FAILED', 'DISCORD_OAUTH_FAILED', 'DISCORD_GUILD_MISMATCH',
        'DISCORD_MEMBER_LOOKUP_FAILED', 'DATABASE_ERROR', 'DATABASE_POOL_EXHAUSTED',
        'UNEXPECTED_EXCEPTION'
    )) NOT VALID;
COMMIT;
ALTER TABLE monitoring_events VALIDATE CONSTRAINT monitoring_events_event_code_check;
