-- Hibernate가 기존 CHECK 제약조건에 새 enum 값을 자동으로 추가하지 못하므로,
-- BingoMissionType을 확장한 운영 DB에서 한 번 실행한다.
ALTER TABLE bingo_cells
    DROP CONSTRAINT IF EXISTS bingo_cells_mission_type_check;

ALTER TABLE bingo_cells
    ADD CONSTRAINT bingo_cells_mission_type_check CHECK (mission_type IN (
        'KILLS', 'DAMAGE_DEALT', 'ASSISTS', 'DBNOS', 'HEADSHOT_KILLS',
        'LONG_DISTANCE_KILL', 'WEAPON_KILLS', 'WEAPON_CATEGORY_KILLS',
        'THROWABLE_KILLS', 'ROAD_KILLS', 'WALL_PENETRATION_KILLS',
        'WINS', 'TOP10', 'SURVIVAL_TIME', 'MATCHES_PLAYED', 'HEALS', 'BOOSTS',
        'WALK_DISTANCE', 'RIDE_DISTANCE', 'SWIM_DISTANCE', 'PARACHUTE_DISTANCE',
        'REVIVES', 'CARRY', 'PLAY_WITH_CLAN_MEMBERS', 'THROWABLE_USED',
        'CARE_PACKAGE_PICKUP', 'FLARE_GUN_USED', 'VAULT_COUNT',
        'LEDGE_GRAB_COUNT', 'WHEEL_DESTROY_COUNT', 'VEHICLE_DESTROY_COUNT',
        'VEHICLE_DAMAGE', 'ARMOR_DESTROY_COUNT', 'FREEFALL_DISTANCE',
        'ITEM_PICKUP', 'ITEM_USE', 'ENEMY_LOOTBOX_PICKUP',
        'EMERGENCY_PICKUP_RIDE', 'BREACHABLE_WALL_DESTROY_COUNT',
        'RIDE_WITH_CLAN_MEMBERS', 'KILL_BET_WIN'
    ));
