package com.guildup.bingo.domain;

public enum BingoMissionType {
    KILLS, DAMAGE_DEALT, ASSISTS, DBNOS, HEADSHOT_KILLS,
    LONG_DISTANCE_KILL, WEAPON_KILLS, WEAPON_CATEGORY_KILLS, THROWABLE_KILLS,
    ROAD_KILLS, WALL_PENETRATION_KILLS, WINS, TOP10, SURVIVAL_TIME,
    MATCHES_PLAYED, HEALS, BOOSTS, WALK_DISTANCE, RIDE_DISTANCE, SWIM_DISTANCE,
    PARACHUTE_DISTANCE, REVIVES, CARRY, PLAY_WITH_CLAN_MEMBERS, THROWABLE_USED,
    CARE_PACKAGE_PICKUP, FLARE_GUN_USED, VAULT_COUNT, LEDGE_GRAB_COUNT,
    WHEEL_DESTROY_COUNT,
    VEHICLE_DESTROY_COUNT, VEHICLE_DAMAGE, ARMOR_DESTROY_COUNT, FREEFALL_DISTANCE,
    ITEM_PICKUP, ITEM_USE, ENEMY_LOOTBOX_PICKUP, EMERGENCY_PICKUP_RIDE,
    BREACHABLE_WALL_DESTROY_COUNT, RIDE_WITH_CLAN_MEMBERS,
    KILL_BET_WIN;

    public BingoMissionSource source() {
        return this == KILL_BET_WIN ? BingoMissionSource.GUILDUP_CONTENT : BingoMissionSource.PUBG_MATCH;
    }
}
