package com.guildup.monitoring.domain;

public enum MonitoringEventCode {
    HTTP_5XX,
    PUBG_API_RATE_LIMIT, PUBG_API_TIMEOUT, PUBG_API_RETRY, PUBG_API_CLIENT_ERROR, PUBG_API_SERVER_ERROR,
    PUBG_API_FAILED,
    COMMUNITY_ACTIVITY_SYNC_FAILED,
    ACTIVITY_SYNC_QUEUED, ACTIVITY_SYNC_STARTED,
    ACTIVITY_SYNC_PLAYER_FETCH_STARTED, ACTIVITY_SYNC_PLAYER_FETCH_COMPLETED, ACTIVITY_SYNC_PLAYER_FETCH_FAILED,
    ACTIVITY_SYNC_MATCH_FETCH_STARTED, ACTIVITY_SYNC_MATCH_FETCH_COMPLETED, ACTIVITY_SYNC_MATCH_FETCH_FAILED,
    ACTIVITY_SYNC_CALCULATION_STARTED, ACTIVITY_SYNC_CALCULATION_COMPLETED,
    ACTIVITY_SYNC_SAVE_STARTED, ACTIVITY_SYNC_SAVE_COMPLETED, ACTIVITY_SYNC_SAVE_FAILED,
    ACTIVITY_SYNC_COMPLETED, ACTIVITY_SYNC_FAILED, ACTIVITY_SYNC_SUPERSEDED,
    PUBG_RATE_LIMIT_RECOVERED,
    BINGO_AGGREGATION_FAILED, BINGO_PARTIAL_FAILURE, BINGO_SLOW_AGGREGATION,
    KILL_COMPETITION_INTERIM_FAILED, KILL_COMPETITION_SETTLEMENT_FAILED,
    KILL_COMPETITION_RESULT_PENDING, KILL_COMPETITION_RESULT_PENDING_STALE,
    DISCORD_API_FAILED, DISCORD_RATE_LIMIT, JDA_CONNECTION_FAILED, DISCORD_GUILD_CONNECTION_FAILED,
    DISCORD_OAUTH_FAILED, DISCORD_GUILD_MISMATCH, DISCORD_MEMBER_LOOKUP_FAILED,
    DATABASE_ERROR, DATABASE_POOL_EXHAUSTED, UNEXPECTED_EXCEPTION
}
