package com.guildup.monitoring.domain;

public enum MonitoringEventCode {
    HTTP_5XX,
    PUBG_API_RATE_LIMIT, PUBG_API_TIMEOUT, PUBG_API_RETRY, PUBG_API_CLIENT_ERROR, PUBG_API_SERVER_ERROR,
    PUBG_API_FAILED,
    BINGO_AGGREGATION_FAILED, BINGO_PARTIAL_FAILURE, BINGO_SLOW_AGGREGATION,
    KILL_COMPETITION_INTERIM_FAILED, KILL_COMPETITION_SETTLEMENT_FAILED,
    KILL_COMPETITION_RESULT_PENDING, KILL_COMPETITION_RESULT_PENDING_STALE,
    DISCORD_API_FAILED, DISCORD_RATE_LIMIT, JDA_CONNECTION_FAILED, DISCORD_GUILD_CONNECTION_FAILED,
    DISCORD_OAUTH_FAILED, DISCORD_GUILD_MISMATCH, DISCORD_MEMBER_LOOKUP_FAILED,
    DATABASE_ERROR, DATABASE_POOL_EXHAUSTED, UNEXPECTED_EXCEPTION
}
